Create Encounter page
se701team3/Forgettable pull request #198
Opened 2022-03-17 01:21 UTC by rushaan01

![image](https://user-images.githubusercontent.com/68492755/158717126-1f579816-6ecd-4750-99ab-0a05b1a09e06.png)

-Page is responsive
-added render test
-API calls yet to be implemented

2022-03-17 02:15 UTC, noahjade reviewed
This is looking really good! Can we change the hard coded fontsize and fontweight to be the css variables? Would also be cool to do this for the colours too, since we want to be able to implement dark theme. You can look in the nav bar component if u need an example of how to get the css vars into the javascript :)

2022-03-17 02:15 UTC, noahjade commented on forgettable-frontend/src/pages/encounters/CreateEncounter.module.css
> +}
Can we use the saved var values in the index css? like var(--text-xxlarge) etc ?

2022-03-17 05:22 UTC, rainasong requested changes

2022-03-17 05:22 UTC, rainasong commented on forgettable-frontend/src/pages/encounters/CreateEncounter.js
> +    alert('Saved');
Should there be an API call to post the new encounter when Save is clicked?

2022-03-18 21:44 UTC, noahjade approved these changes
Thanks for your hard work rushaan!! Lets get this merged so people can help out on the API call stuff :)

2022-03-18 22:00 UTC, rainasong approved these changes

2022-03-18 22:03 UTC, noahjade requested changes
Just realised this cant actually be merged!!

2022-03-19 12:26 UTC, closed without merging