Added Dialog Component
se701team3/Forgettable pull request #96
Opened 2022-03-10 11:51 UTC by jyao244

Finished Dialog and added a testing file for testing dialog.

2022-03-10 13:00 UTC, hajineats commented
Could someone clarify if this is for the middle modal component here? 

<img width="612" alt="Screen Shot 2022-03-11 at 1 57 13 AM" src="https://user-images.githubusercontent.com/68993476/157666446-b9b6f996-02a3-4a52-bc0f-85a11fcff760.png">

Would be nice if someone could clarify acceptance criteria for this (eg does this component need to contain logic for modal, or will there be a modal component?)

2022-03-10 13:16 UTC, hajineats requested changes
Hi Jiayou! Appreciate the time you took to create these changes. I've left comments here and there that might be helpful for you. Feel free to ping me if you need any help or clarification regarding these. Another side note, commented out codes should generally be avoided in production codes. Thanks!

2022-03-10 13:16 UTC, hajineats commented on forgettable-frontend/src/components/Dialog/Dialog.js
> +  const {title, desc, cancalEvent, confirmEvent} = props;
Variable names should preferably be spelled in full as it helps other devs.

2022-03-10 13:16 UTC, hajineats commented on forgettable-frontend/src/components/Dialog/Dialog.js
> +    <div className={classes.toolbar}>
classes.toolbar is not in the Dialog.module.css file

2022-03-10 13:16 UTC, hajineats commented on forgettable-frontend/src/components/Dialog/Dialog.js
> +      <button className={classes.button2} onClick={confirmEvent}>Confirm</button>
These two buttons share the same style so reusing one of the css classes would be a better option here

2022-03-10 13:16 UTC, hajineats commented on forgettable-frontend/src/components/Dialog/Dialog.module.css
> +  transform: translate(-50%, -50%);
There's a really useful mui (material ui) component called [Modal](https://mui.com/components/modal/#main-content). That will make css a lot more concise (no need to use fixed, top, left, translate, zindex as it automatically centers it for you!)

2022-03-10 13:16 UTC, hajineats commented on forgettable-frontend/src/components/Dialog/Dialog.module.css
> +  margin-right: 123px;
`text-align: center` would be better here as we want to generally avoid hardcoding values

2022-03-10 19:49 UTC, rainasong commented
> Could someone clarify if this is for the modal component on the right?
> 
> <img alt="Screen Shot 2022-03-11 at 1 57 13 AM" width="612" src="https://user-images.githubusercontent.com/68993476/157666446-b9b6f996-02a3-4a52-bc0f-85a11fcff760.png">
> 
> Would be nice if someone could clarify acceptance criteria for this (eg does this component need to contain logic for modal, or will there be a modal component?)
> 
> Also what should the title color/size be?

Thanks for bring this up and sorry if it's not clear in the issue.
The modal should cover all three cases below:
<img width="877" alt="Screen Shot 2022-03-11 at 8 26 09 AM" src="https://user-images.githubusercontent.com/37087904/157739497-db0744c0-72b4-4ae1-bcad-fce098f918f8.png">
- The title should be semibold, 30px (--text-xxlarge), *users should be able to specify the colour of the title. 
- The body of the modal should be configurable outside the modal component, as you can see we not only have cases where description is needed but also cases where we want buttons/input fields. This means users should be able to pass JSX/react component in as the children of the component from outside. (an example is as below)
![Screen Shot 2022-03-11 at 8 41 31 AM](https://user-images.githubusercontent.com/37087904/157741979-53efd30c-e600-48ca-8e77-747886ae908c.png)
https://reactjs.org/docs/composition-vs-inheritance.html
- Users should be able to choose if they want 'Cancel' and 'Confirm' button or just 'Cancel' button.
- As described in this #64 issue here the modal should be able to close by clicking anywhere outside the modal area as well.
- I would recommend using the material UI modal component as the base and modify the styles as it will be easier and you can also add transitions and other effects later more easily. https://mui.com/components/modal/
(*User here means anyone who's using this component)

Please feel free to ask for further clarifications if you have any questions, and if anyone else has questions feel free to ask as well!

2022-03-10 19:57 UTC, rainasong requested changes
Hey Jiayou! Thanks for your hard work!
Please have a look at the comment I made above and if possible, make some changes to cover those clarified acceptance criteria. Sorry it wasn't very clear in the issue!
Thanks!

2022-03-10 19:57 UTC, rainasong commented on forgettable-frontend/src/components/Dialog/Dialog.js
> +function Dialog(props) {
Can we please change 'Dialog' to 'Modal' as it will be consistent with the issue.

2022-03-14 21:52 UTC, rainasong commented
Updated Modal component (name changed to CustomModal) to be able to accept children components. Styles are also able to be passed in from outside by specifying className variable.
By specifying 'hasCancel', 'hasConfirm' can add the default cancel or confirm button. If 'hasConfirm' is specified, 'onConfirm' function should be passed in as well.
Users are able to click anywhere outside the Modal to close it, or they can click on the Cancel button.

Currently this component can taking following props:
`CustomModal.propTypes = {
  open: PropTypes.bool.isRequired,
  hasCancel: PropTypes.bool,
  hasConfirm: PropTypes.bool,
  onClose: PropTypes.func.isRequired,
  onConfirm: PropTypes.func,
  className: PropTypes.string,
};`

Examples as below:
![Screen Shot 2022-03-15 at 10 38 34 AM](https://user-images.githubusercontent.com/37087904/158265828-30cdff11-565c-44d8-b247-678164ea059d.png)

2022-03-14 21:54 UTC, rainasong approved these changes

2022-03-14 22:24 UTC, noahjade approved these changes
Thanks for your work on this guys!!

2022-03-15 00:09 UTC, hajineats approved these changes

2022-03-15 00:19 UTC, merged